#######################
# Theme Customization #
#######################

title: Shubham Sharma          # appears in the header and the HTML <title> tag
author: Shubham Sharma     # appears in an HTML <meta> tag, as well as feed.xml
description: >           # appears in an HTML <meta> tag, as well as feed.xml

slogan: Lets Code        # appears in the header, alongside the title
avatar: /i/avatar.png    # appears as portrait in the header
banner: /i/mountains.svg # appears as background in the header
url: http://jekyllrb.com # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''              # prepended to all absolute filepaths
repo: https://github.com//smsharma1.github.io # appears in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/smsharma1/
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: hello       # you know, to protect you from bots. (handle and domain
    domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
